export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADD_TO_SAVED_FOR_LATER = "ADD_TO_SAVED_FOR_LATER";

export const GET_CART_CONTENT_REQUEST = "GET_CART_CONTENT_REQUEST";
export const GET_CART_CONTENT_SUCCESS = "GET_CART_CONTENT_SUCCESS";
export const GET_CART_CONTENT_FAIL = "GET_CART_CONTENT_FAIL";
